creation_rules:
  - path_regex: secrets/github.yaml
    key_groups:
      - age:
          # -- @sportshead
          # v1.mbair.se
          - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          # backup
          - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf

          # deploy-ghcr
          - age1ydwmjxyks759l03gm5qde3k6xmhq7nkpd5qlhlrzgf8h4tngep9s0uay85
          # deploy-challenge-yamls
          - age1628lld7k7gvkrc3vpaqkpcf9tz2jhaqwsjneeuwv9dpa0l45jeysywnrpp
  - path_regex: secrets/attachments.yaml
    key_groups:
      - age:
          # -- @sportshead
          # v1.mbair.se
          - age1tag1qw6cx6k7s34zt378mgwlmcy4jq4jdzgs4auuwlugyhx8td59wg96q8kyajc
          # backup
          - age1chacvhtf5y0vjvh7a762780t84846h8hl72wskjcr99a3qjylgxse30hdf

          # deploy-attachments
          - age16v6kdyznrt6v2hc2f7rc2p9nrwcne9ylml7urwukn780asadq54qu60d49
