apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: attachment
spec:
  author: Donald Trump
  flag: gaslightCTF{can-you-read}
  flagFormat: gaslightCTF{...}
  description: |
    Do you know how to download a file?
  difficulty: easy
  categories:
    - forensics
  tags:
    - template
