apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: messageboard
spec:
  author: sportshead
  flag: gaslightCTF{ar3_y0u_my_cl0s3_fr13nd_n0w?}
  flagFormat: gaslightCTF{...}
  description: |
    I left a little message for only my closest friends :)
  difficulty: easy
  categories:
    - web
  containers:
    - hostname: messageboard
      image: CHALLENGE_IMAGE
      ports:
        - port: 3000
          protocol: tcp
          appProtocol: http
          type: publicHttpRoute
      dynamicFlag:
        env:
          name: FLAG

    - hostname: db
      image: CHALLENGE_IMAGE_messageboard-db
