apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: container
spec:
  author: Donald Trump
  flag: gaslightCTF{hello_pwn}
  flagFormat: gaslightCTF{...}
  description: |
    Hello world! <i>italics</i> <b>bold</b>
  difficulty: easy
  categories:
    - pwn
  tags:
    - template
  containers:
    - hostname: chall
      image: CHALLENGE_IMAGE
      ports:
        - port: 1337
          protocol: tcp
          appProtocol: tcp
          type: publicTlsRoute
      dynamicFlag:
        env:
          name: FLAG
