apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: 4-piece-puzzle
spec:
  displayName: 4-piece-puzzle
  author: riyc
  flag: gaslightCTF{i_4m_f0ur_y3ars_01d}
  flagFormat: gaslightCTF{...}
  description: |
    these <b>fou-fou-four</b> puzzle pieces are my favorite colours! excuse the stutter.
  difficulty: medium
  categories:
    - forensics