apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: corridors
spec:
  hideUntil: WAVE_1
  author: sportshead
  flag: gaslightCTF{fr33d0m_4t_l4st}
  flagFormat: gaslightCTF{...}
  description: |
    The path will guide you to the flag.
  difficulty: easy
  categories:
    - web
  containers:
    - hostname: corridors
      image: CHALLENGE_IMAGE
      ports:
        - port: 3000
          protocol: tcp
          appProtocol: http
          type: publicHttpRoute
      dynamicFlag:
        env:
          name: FLAG
