apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: down-the-stream-1
spec:
  hideUntil: WAVE_1
  author: william_etotheipi
  flag: gaslightCTF{d0nt-r3veal-y0ur-co3ff-v3ct0r}
  flagFormat: gaslightCTF{...}
  description: |
    A synchronous stream cipher sounds like a very secure cipher!
  difficulty: medium
  categories:
    - crypto
